# Generated by Django 3.1.1 on 2022-05-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutskills',
            options={'verbose_name': 'スキル', 'verbose_name_plural': 'スキル'},
        ),
    ]
