# Generated by Django 3.1.1 on 2022-03-25 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attack_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': '攻撃方法',
                'verbose_name_plural': '攻撃方法',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('explanation', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'スペシャル',
                'verbose_name_plural': 'スペシャル一覧',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('explanation', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'スペシャル',
                'verbose_name_plural': 'スペシャル一覧',
            },
        ),
        migrations.CreateModel(
            name='SubWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
                ('explanation', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': 'サブウェポン',
                'verbose_name_plural': 'サブウェポン一覧',
            },
        ),
        migrations.CreateModel(
            name='Weapon_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': 'ブキ種',
                'verbose_name_plural': 'ブキ種一覧',
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名前')),
            ],
            options={
                'verbose_name': '重量',
                'verbose_name_plural': '重量',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='ブキ名')),
                ('sp_point', models.IntegerField(default=0)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.main')),
                ('special', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.special')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.subweapon')),
            ],
            options={
                'verbose_name': 'ブキ',
                'verbose_name_plural': 'ブキ',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='射程')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.main')),
                ('range_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.attack_class')),
            ],
            options={
                'verbose_name': '射程',
                'verbose_name_plural': '射程',
            },
        ),
        migrations.AddField(
            model_name='main',
            name='attacks',
            field=models.ManyToManyField(through='spla.Range', to='spla.Attack_class'),
        ),
        migrations.AddField(
            model_name='main',
            name='weapon_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.weapon_class'),
        ),
        migrations.AddField(
            model_name='main',
            name='weight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='spla.weight'),
        ),
    ]
