# Generated by Django 3.1.1 on 2022-03-25 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'メイン', 'verbose_name_plural': 'メイン一覧'},
        ),
    ]
