# Generated by Django 3.1.1 on 2022-03-27 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0002_auto_20220325_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'ブキ', 'verbose_name_plural': 'ブキ一覧'},
        ),
    ]
