# Generated by Django 3.1.1 on 2022-03-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0003_auto_20220327_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='special',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subweapon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weapon_class',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
