# Generated by Django 3.1.1 on 2022-03-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0004_auto_20220327_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon_class',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
    ]
