# Generated by Django 3.1.1 on 2022-03-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0005_weapon_class_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
