# Generated by Django 3.1.1 on 2022-03-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0006_auto_20220330_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main_img'),
        ),
        migrations.AddField(
            model_name='special',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sp_img'),
        ),
        migrations.AddField(
            model_name='subweapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sub_img'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weapon_img'),
        ),
    ]
