# Generated by Django 3.1.1 on 2022-04-14 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0008_auto_20220403_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='range', to='spla.main'),
        ),
        migrations.AlterField(
            model_name='range',
            name='range_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='range', to='spla.attack_class'),
        ),
    ]
