# Generated by Django 4.0.6 on 2022-07-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spla', '0009_auto_20220414_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attack_class',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='range',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
